import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React from 'react';
import { useAuth0 } from '@auth0/auth0-react';
import TitleHeading from '../componentes/titleHeading';
import headingImg from '../images/Title-heading.png';
import headingImgPhone from '../images/Title-heading-movil.png';
import AlternateHeadline from '../componentes/alternateheadline';
import SelectionCourses from '../componentes/selectionofcourses';
import TopCategoriesHome from '../componentes/topcategorieshome';
import BecomeInstructorHome from '../componentes/becomeInstructorHome';
import BecomeInstructorMobile from '../images/BecomeInstructorMobilejpg.jpg';
import BecomeInstructor from '../images/BecomeInstructor.jpg';
import Footer from '@/componentes/footer';

import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { user, isAuthenticated } = useAuth0();
  return (
    <>
      <Head>
        <title>Log | Udemy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className="home-container">
      <TitleHeading
       title='Last day for these savings!'
       text='Courses that meet today’s challenges (and tomorrow’s). They start at just COL$39,900. Sale ends today.'
       img={headingImg}
       alt='illustration'
       imgPhone={headingImgPhone}
       />      
      <AlternateHeadline
      title='A broad selection of courses'
      info='Choose from 204,000 online video courses with new additions published every month'
      />
      <SelectionCourses />
      <TopCategoriesHome
      title='Top Categories'
      />
{/* // !userInfo.isInstructor */}
{ (true) 
      ?
      <BecomeInstructorHome 
      img={BecomeInstructor}
      title='Become an instructor'
      info='Instructors from around the world teach millions of students on Udemy. We provide the tools and skills to teach what you love.'
      btn='Start teaching today'
      imgMobile={BecomeInstructorMobile}
    />
    :
    null
    }

      <Footer />




   


      

        {/* <div className={styles.grid}>
          <nav>
            <ul>
              <li>
                <Link href='/'>Home</Link>
              </li>
              <li>
                <Link href='/about' >About</Link>
              </li>
              <li>
                <Link href='/products' >Products</Link>
              </li>
            </ul>
          </nav>
        </div> */}
        </div>
     
    </>
  )
}
